### ISSUE TITLE
Remove the word "alexa" when using short utterances

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#473]
**Preconditions**
- Set trace=true in the testing.json file
- Set up an end to end test that uses "yes/no" questions. You can take this one as an example:

```
---
configuration:
  locale: en-US
  voiceId: Joey
  virtualDeviceToken: <a token>

---
- test: Animal game
- start animal game: animal
- yes: is it
- no: is it
```

**Steps To Reproduce**
1. Launch bst test with the above test

**Expected behavior**
The same messages that were written should be sent to AVS.

**Actual behavior**
The second and third messages have been changed to "alexa yes" and "alexa no". (you can see that on the trace)

**Environment:**
 - BST v2.0.9

**Additional context**
I think this was added because at some point we thought that TTS was not working correctly with short utterances. However, this is preventing us from going forward in creating scripts for google assistant and it also adds the word "alexa" with other non-ascii languages.

Also, the issue might come from virtual-device-sdk. If so, create an issue in that project and reference this issue here. So that the sdk package version is updated when that's done.
