### ISSUE TITLE
bst init

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#595]
**Is your feature request related to a problem? Please describe.**
We want bst to be as friendly as possible for new users, for that, an init script will be helpful as it will set up everything nicely for a first time use.

**Describe the solution you'd like**
When typing `bst init` the following should happen:

```
Welcome to the bespoken tools CLI. 
We'll set up all you need for you to start testing your voice apps. 
Please tell us:

Are you looking to create:
1 - unit tests
2 - e2e tests

Please type your option (1 or 2) :
```

```
What's the name of your voice app?:
```

```
What platform are you developing for?
1 - amazon alexa
2 - google assistant

Please type your option (1 or 2) :
```

```
Does your voice app target multiple languages? 
If so, please type your locales separated by a comma. 
If not leave blank for the default (en-US) and press enter.

Type your locales:
```

Only if the user has picked e2e:
```
For e2e tests, type in your virtual device token. 
If you don't have one or are not sure just leave it blank. 
You can create virtual devices here: https://apps.bespoken.io/dashboard/virtualdevice

Type in your token: 
```

With this information, we should create a structure starting from the current folder as explained in read.bespoken.io: https://read.bespoken.io/unit-testing/faq/#how-should-i-organize-my-test-files. That means this structure (if multi-locale):

- test
  - unit
    - index.test.yml
    - testing.json
    - locales
      - en-US.yml
      - de-DE.yml

  - e2e
    - index.test.yml
    - testing.json
    - locales
      - en-US.yml
      - de-DE.yml

And this other one (if only using one locale):

- test
  - unit
    - index.test.yml
    - testing.json

  - e2e
    - index.test.yml
    - testing.json

The testing.json files should look like this (virtual device token should be the one provided by the user. Otherwise, it should just say "your virtual device token goes here":

```json
{   
    "virtualDeviceToken": "alexa-xxxx-xxxx-xxxx-xxxxx-",
    "locales": "en-US, de-DE",
    "type":"e2e"
}
```

and

```javascript
{
    "handler": "relative or absolute path to your voice app entry point",
    "locales": "en-US, de-DE",
}
```

The yml test files should have a basic test like this:

- For unit testing (single locale): 
```yml
# This is the test file for your unit tests, feel free to copy and modify the template test 
# for your voice app as many times as you want. On this same folder, you'll also find a testing.json 
# file, it contains global configurations for future test files you might create in the future.
# 
# Find more info on https://read.bespoken.io/end-to-end/getting-started/
---
configuration:
    description: My first unit test suite

---
- test: Launch and ask for help
- LaunchRequest: Welcome to MY VOICE APP NAME
- AMAZON.HelpIntent: 
  - prompt: What can I help you with?
  - cardContent: What can I help you with?
  - cardTitle: MY VOICE APP NAME
```

- For unit testing (multi locale): 
```yml
# This is the test file for your unit tests, feel free to copy and modify the template test 
# for your voice app as many times as you want. On this same folder you'll also find a testing.json 
# file, it contains global configurations for future test files you might create in the future.
# You'll also find a folder called locales, it contains the localization files for all your supported
# locales. Just put a value to each variable and they will be replaced here. Add, remove or modify 
# as necessary.
#
# Find more info on https://read.bespoken.io/end-to-end/getting-started/
---
configuration:
    description: testSuiteDescription

---
- test: firstTestName
- LaunchRequest: launchPrompt
- AMAZON.HelpIntent: 
  - prompt: helpPrompt
  - cardContent: helpCardContent
  - cardTitle: helpCardTitle
```

Additionally, there should be a file for each locale. For english we can use the values that we are using on the single locale file. For other locales, we can just leave the parameter values blank.

Eg. english:

```yml
# This is the localization file for en-US. Please, modify the values so that they align 
# with your voice app responses for this locale

testSuiteDescription: My first unit test suite
firstTestName: Launch and ask for help
launchPrompt: Welcome to MY VOICE APP NAME
helpPrompt: What can I help you with?
helpCardContent: What can I help you with?
helpCardTitle: MY VOICE APP NAME
```

- For e2e testing (single locale): 
```yml

# This is the test file for your e2e tests, feel free to copy and modify the template test 
# for your voice app as many times as you want. On this same folder you'll also find a testing.json 
# file, it contains global configurations for future test files you might create in the future.
#
# Find more info on https://read.bespoken.io/end-to-end/getting-started/
---
configuration:
    description: My first e2e test suite
---
- test: Launch and ask for help
- open MY VOICE APP NAME: Welcome to MY VOICE APP NAME
- help:
  - prompt: What can I help you with?
  - cardContent: What can I help you with?
  - cardTitle: MY VOICE APP NAME
```

- For e2e testing (multi locale):
```yml

# This is the test file for your e2e tests, feel free to copy and modify the template test 
# for your voice app as many times as you want. On this same folder you'll also find a testing.json 
# file, it contains global configurations for future test files you might create in the future.
# You'll also find a folder called locales, it contains the localization files for all your supported
# locales. Just put a value to each variable and they will be replaced here. Add, remove or modify 
# as necessary.
#
# Find more info on https://read.bespoken.io/end-to-end/getting-started/
---
configuration:
    description: testSuiteDescription
---
- test: firstTestName
- launchUtterance: launchPrompt
- helpUtterance:
  - prompt: helpPrompt
  - cardContent: helpCardContent
  - cardTitle: helpCardTitle
```

Same as for the unit tests, a localization file should be created for every specified locale. We'll follow the approach previously descripted and will also add localized utterances for e2e tests.
