### ISSUE TITLE
add IVR support to bst init

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#655]
**Summary**
Now that we've simplified our IVR tests, we want to make this easier to setup by adding support for them on bst init.

**Description**
The bst init command should also include an option for IVR tests. As such, the first option should say:
```
Welcome to the Bespoken CLI.
We'll set up all you need to start testing your voice experiences.
Please tell us:
? What type of tests are you creating - unit or end-to-end (Use arrow keys)
❯ unit 
  end-to-end
```

Selecting end-to-end should show:

```
Enter the name of your voice experience: (voice hello world)
```

The next question should be: 

```
Are you developing for Alexa, Google, or an IVR system? (Use arrow keys)
❯ Alexa 
  Google 
  IVR
```

Selecting IVR should ask this next:
```
Please provide a valid phone number in the E.164 format to call to (e.g.: +14155552671):
```

This last question is required. If the user leaves it blank or enters an invalid number, the question should be repeated.

Finally, we'll ask for the token in the same way we do now.

After all the questions, the resulting test should look like this:

```yaml
# This is the test file for your e2e tests, feel free to copy and modify the template test
# as many times as you want. On this same folder, you'll also find a testing.json
# file, it contains global configurations for future test files you might create in the future.
#
# Find more info on https://read.bespoken.io/end-to-end/getting-started/
---
configuration:
  description: My first e2e test suite
---
- test : Dial and say hello
- $DIAL : 
  - transcript: Welcome to <voice experience name>
  - set finishOnPhrase: what can I help you with?
```

The testing.json should look like this:
```json
{
    "virtualDeviceToken": "[your virtual device token goes here]",
    "locales": "en-US",
    "type": "e2e",
    "platform": "twilio",
    "phoneNumber": "phone number"
}
```
